export const BANKS = [
  "BCA",
  "Mandiri",
  "BNI",
  "BRI",
  "CIMB Niaga",
  "Danamon",
  "Permata",
  "BSI",
  "OCBC",
  "UOB",
  "Panin",
  "BTN",
  "Jago",
  "Seabank",
  "Allo Bank",
  "Neo Commerce",
  "Muamalat",
  "Bukopin",
  "Sinarmas",
  "Mega",
  "Sahabat Sampoerna",
  "Artos",
  "Ganesha",
  "Index Selindo",
  "Mestika Dharma",
  "Shinhan",
  "Woori Saudara",
  "BTPN",
  "BTPN Syariah",
  "Prima Master",
  "Banten",
  "Dinar",
  "Kesejahteraan Ekonomi",
  "Yudha Bhakti",
  "Maspion",
  "Mega Syariah",
  "Aladin Syariah",
  "BPRKS",
  "BPR Daeng Bandung",
  "BPR Karyajatnika Sadaya",
] as const;

export const E_WALLETS = [
  "GoPay",
  "OVO",
  "DANA",
  "ShopeePay",
  "LinkAja",
  "Sakuku",
  "iSaku",
  "MaximPay",
] as const;

export const PAYMENT_PROVIDERS = [...BANKS, ...E_WALLETS] as const;
