// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: konkosyuk/v1/notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationCategory int32

const (
	NotificationCategory_NOTIFICATION_CATEGORY_UNSPECIFIED NotificationCategory = 0
	NotificationCategory_BOOKING                           NotificationCategory = 1
	NotificationCategory_PAYMENT                           NotificationCategory = 2
	NotificationCategory_MAINTENANCE                       NotificationCategory = 3
	NotificationCategory_INSPECTION                        NotificationCategory = 4
	NotificationCategory_CHAT                              NotificationCategory = 5
	NotificationCategory_REVIEW                            NotificationCategory = 6
	NotificationCategory_SYSTEM                            NotificationCategory = 7
)

// Enum value maps for NotificationCategory.
var (
	NotificationCategory_name = map[int32]string{
		0: "NOTIFICATION_CATEGORY_UNSPECIFIED",
		1: "BOOKING",
		2: "PAYMENT",
		3: "MAINTENANCE",
		4: "INSPECTION",
		5: "CHAT",
		6: "REVIEW",
		7: "SYSTEM",
	}
	NotificationCategory_value = map[string]int32{
		"NOTIFICATION_CATEGORY_UNSPECIFIED": 0,
		"BOOKING":                           1,
		"PAYMENT":                           2,
		"MAINTENANCE":                       3,
		"INSPECTION":                        4,
		"CHAT":                              5,
		"REVIEW":                            6,
		"SYSTEM":                            7,
	}
)

func (x NotificationCategory) Enum() *NotificationCategory {
	p := new(NotificationCategory)
	*p = x
	return p
}

func (x NotificationCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_konkosyuk_v1_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationCategory) Type() protoreflect.EnumType {
	return &file_konkosyuk_v1_notification_proto_enumTypes[0]
}

func (x NotificationCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationCategory.Descriptor instead.
func (NotificationCategory) EnumDescriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_LOW                               NotificationPriority = 1
	NotificationPriority_NORMAL                            NotificationPriority = 2
	NotificationPriority_HIGH                              NotificationPriority = 3
	NotificationPriority_URGENT                            NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "LOW",
		2: "NORMAL",
		3: "HIGH",
		4: "URGENT",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"LOW":                               1,
		"NORMAL":                            2,
		"HIGH":                              3,
		"URGENT":                            4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_konkosyuk_v1_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_konkosyuk_v1_notification_proto_enumTypes[1]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{1}
}

type EmailDigest int32

const (
	EmailDigest_EMAIL_DIGEST_UNSPECIFIED EmailDigest = 0
	EmailDigest_IMMEDIATE                EmailDigest = 1
	EmailDigest_DAILY                    EmailDigest = 2
	EmailDigest_WEEKLY                   EmailDigest = 3
	EmailDigest_NEVER                    EmailDigest = 4
)

// Enum value maps for EmailDigest.
var (
	EmailDigest_name = map[int32]string{
		0: "EMAIL_DIGEST_UNSPECIFIED",
		1: "IMMEDIATE",
		2: "DAILY",
		3: "WEEKLY",
		4: "NEVER",
	}
	EmailDigest_value = map[string]int32{
		"EMAIL_DIGEST_UNSPECIFIED": 0,
		"IMMEDIATE":                1,
		"DAILY":                    2,
		"WEEKLY":                   3,
		"NEVER":                    4,
	}
)

func (x EmailDigest) Enum() *EmailDigest {
	p := new(EmailDigest)
	*p = x
	return p
}

func (x EmailDigest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmailDigest) Descriptor() protoreflect.EnumDescriptor {
	return file_konkosyuk_v1_notification_proto_enumTypes[2].Descriptor()
}

func (EmailDigest) Type() protoreflect.EnumType {
	return &file_konkosyuk_v1_notification_proto_enumTypes[2]
}

func (x EmailDigest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmailDigest.Descriptor instead.
func (EmailDigest) EnumDescriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{2}
}

type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_IN_APP              Channel = 1
	Channel_EMAIL               Channel = 2
	Channel_PUSH                Channel = 3
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "IN_APP",
		2: "EMAIL",
		3: "PUSH",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"IN_APP":              1,
		"EMAIL":               2,
		"PUSH":                3,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_konkosyuk_v1_notification_proto_enumTypes[3].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_konkosyuk_v1_notification_proto_enumTypes[3]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{3}
}

type ChannelPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InApp         bool                   `protobuf:"varint,1,opt,name=in_app,json=inApp,proto3" json:"in_app,omitempty"`
	Email         bool                   `protobuf:"varint,2,opt,name=email,proto3" json:"email,omitempty"`
	Push          bool                   `protobuf:"varint,3,opt,name=push,proto3" json:"push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelPreferences) Reset() {
	*x = ChannelPreferences{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelPreferences) ProtoMessage() {}

func (x *ChannelPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelPreferences.ProtoReflect.Descriptor instead.
func (*ChannelPreferences) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelPreferences) GetInApp() bool {
	if x != nil {
		return x.InApp
	}
	return false
}

func (x *ChannelPreferences) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *ChannelPreferences) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

type UserPreferences struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Preferences     map[string]*ChannelPreferences `protobuf:"bytes,1,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmailDigest     EmailDigest                    `protobuf:"varint,2,opt,name=email_digest,json=emailDigest,proto3,enum=konkosyuk.v1.EmailDigest" json:"email_digest,omitempty"`
	QuietHoursStart string                         `protobuf:"bytes,3,opt,name=quiet_hours_start,json=quietHoursStart,proto3" json:"quiet_hours_start,omitempty"`
	QuietHoursEnd   string                         `protobuf:"bytes,4,opt,name=quiet_hours_end,json=quietHoursEnd,proto3" json:"quiet_hours_end,omitempty"`
	Timezone        string                         `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *UserPreferences) GetPreferences() map[string]*ChannelPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UserPreferences) GetEmailDigest() EmailDigest {
	if x != nil {
		return x.EmailDigest
	}
	return EmailDigest_EMAIL_DIGEST_UNSPECIFIED
}

func (x *UserPreferences) GetQuietHoursStart() string {
	if x != nil {
		return x.QuietHoursStart
	}
	return ""
}

func (x *UserPreferences) GetQuietHoursEnd() string {
	if x != nil {
		return x.QuietHoursEnd
	}
	return ""
}

func (x *UserPreferences) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type NotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Category      NotificationCategory   `protobuf:"varint,3,opt,name=category,proto3,enum=konkosyuk.v1.NotificationCategory" json:"category,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,4,opt,name=priority,proto3,enum=konkosyuk.v1.NotificationPriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,7,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	ActionLabel   string                 `protobuf:"bytes,8,opt,name=action_label,json=actionLabel,proto3" json:"action_label,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,9,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	ReferenceType string                 `protobuf:"bytes,10,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationEvent) GetCategory() NotificationCategory {
	if x != nil {
		return x.Category
	}
	return NotificationCategory_NOTIFICATION_CATEGORY_UNSPECIFIED
}

func (x *NotificationEvent) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *NotificationEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationEvent) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

func (x *NotificationEvent) GetActionLabel() string {
	if x != nil {
		return x.ActionLabel
	}
	return ""
}

func (x *NotificationEvent) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *NotificationEvent) GetReferenceType() string {
	if x != nil {
		return x.ReferenceType
	}
	return ""
}

func (x *NotificationEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DispatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChannelResults map[string]bool        `protobuf:"bytes,2,rep,name=channel_results,json=channelResults,proto3" json:"channel_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchResponse) GetChannelResults() map[string]bool {
	if x != nil {
		return x.ChannelResults
	}
	return nil
}

func (x *DispatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DispatchBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*NotificationEvent   `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchBatchRequest) Reset() {
	*x = DispatchBatchRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchBatchRequest) ProtoMessage() {}

func (x *DispatchBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchBatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchBatchRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchBatchRequest) GetEvents() []*NotificationEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type DispatchBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DispatchResponse    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchBatchResponse) Reset() {
	*x = DispatchBatchResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchBatchResponse) ProtoMessage() {}

func (x *DispatchBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchBatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchBatchResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DispatchBatchResponse) GetResults() []*DispatchResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,6,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	IsRead        bool                   `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PushSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh        string                 `protobuf:"bytes,4,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth          string                 `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSubscription) Reset() {
	*x = PushSubscription{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSubscription) ProtoMessage() {}

func (x *PushSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSubscription.ProtoReflect.Descriptor instead.
func (*PushSubscription) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *PushSubscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PushSubscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushSubscription) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PushSubscription) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *PushSubscription) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *PushSubscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type NotificationSettings struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Id                             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResendApiKey                   string                 `protobuf:"bytes,2,opt,name=resend_api_key,json=resendApiKey,proto3" json:"resend_api_key,omitempty"`
	ResendFromEmail                string                 `protobuf:"bytes,3,opt,name=resend_from_email,json=resendFromEmail,proto3" json:"resend_from_email,omitempty"`
	MetaAccessToken                string                 `protobuf:"bytes,4,opt,name=meta_access_token,json=metaAccessToken,proto3" json:"meta_access_token,omitempty"`
	MetaPhoneNumberId              string                 `protobuf:"bytes,5,opt,name=meta_phone_number_id,json=metaPhoneNumberId,proto3" json:"meta_phone_number_id,omitempty"`
	MetaMaintenanceCreatedTemplate string                 `protobuf:"bytes,6,opt,name=meta_maintenance_created_template,json=metaMaintenanceCreatedTemplate,proto3" json:"meta_maintenance_created_template,omitempty"`
	MetaMaintenanceUpdatedTemplate string                 `protobuf:"bytes,7,opt,name=meta_maintenance_updated_template,json=metaMaintenanceUpdatedTemplate,proto3" json:"meta_maintenance_updated_template,omitempty"`
	CreatedAt                      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                      string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettings) ProtoMessage() {}

func (x *NotificationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSettings.ProtoReflect.Descriptor instead.
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationSettings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationSettings) GetResendApiKey() string {
	if x != nil {
		return x.ResendApiKey
	}
	return ""
}

func (x *NotificationSettings) GetResendFromEmail() string {
	if x != nil {
		return x.ResendFromEmail
	}
	return ""
}

func (x *NotificationSettings) GetMetaAccessToken() string {
	if x != nil {
		return x.MetaAccessToken
	}
	return ""
}

func (x *NotificationSettings) GetMetaPhoneNumberId() string {
	if x != nil {
		return x.MetaPhoneNumberId
	}
	return ""
}

func (x *NotificationSettings) GetMetaMaintenanceCreatedTemplate() string {
	if x != nil {
		return x.MetaMaintenanceCreatedTemplate
	}
	return ""
}

func (x *NotificationSettings) GetMetaMaintenanceUpdatedTemplate() string {
	if x != nil {
		return x.MetaMaintenanceUpdatedTemplate
	}
	return ""
}

func (x *NotificationSettings) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NotificationSettings) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UserNotificationPreferences struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Id              string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                         `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences     map[string]*ChannelPreferences `protobuf:"bytes,3,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmailDigest     EmailDigest                    `protobuf:"varint,4,opt,name=email_digest,json=emailDigest,proto3,enum=konkosyuk.v1.EmailDigest" json:"email_digest,omitempty"`
	QuietHoursStart string                         `protobuf:"bytes,5,opt,name=quiet_hours_start,json=quietHoursStart,proto3" json:"quiet_hours_start,omitempty"`
	QuietHoursEnd   string                         `protobuf:"bytes,6,opt,name=quiet_hours_end,json=quietHoursEnd,proto3" json:"quiet_hours_end,omitempty"`
	Timezone        string                         `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	UpdatedAt       string                         `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserNotificationPreferences) Reset() {
	*x = UserNotificationPreferences{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNotificationPreferences) ProtoMessage() {}

func (x *UserNotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNotificationPreferences.ProtoReflect.Descriptor instead.
func (*UserNotificationPreferences) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *UserNotificationPreferences) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserNotificationPreferences) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserNotificationPreferences) GetPreferences() map[string]*ChannelPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UserNotificationPreferences) GetEmailDigest() EmailDigest {
	if x != nil {
		return x.EmailDigest
	}
	return EmailDigest_EMAIL_DIGEST_UNSPECIFIED
}

func (x *UserNotificationPreferences) GetQuietHoursStart() string {
	if x != nil {
		return x.QuietHoursStart
	}
	return ""
}

func (x *UserNotificationPreferences) GetQuietHoursEnd() string {
	if x != nil {
		return x.QuietHoursEnd
	}
	return ""
}

func (x *UserNotificationPreferences) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserNotificationPreferences) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNotificationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNotificationRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *GetUnreadCountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{13}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{14}
}

func (x *MarkReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{15}
}

func (x *MarkReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribePushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh        string                 `protobuf:"bytes,3,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth          string                 `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePushRequest) Reset() {
	*x = SubscribePushRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePushRequest) ProtoMessage() {}

func (x *SubscribePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePushRequest.ProtoReflect.Descriptor instead.
func (*SubscribePushRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribePushRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribePushRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *SubscribePushRequest) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *SubscribePushRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type SubscribePushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePushResponse) Reset() {
	*x = SubscribePushResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePushResponse) ProtoMessage() {}

func (x *SubscribePushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePushResponse.ProtoReflect.Descriptor instead.
func (*SubscribePushResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribePushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *Empty                 `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{18}
}

func (x *GetSettingsRequest) GetEmpty() *Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *NotificationSettings  `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{19}
}

func (x *GetSettingsResponse) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateNotificationSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *NotificationSettings  `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsRequest) Reset() {
	*x = UpdateNotificationSettingsRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsRequest) ProtoMessage() {}

func (x *UpdateNotificationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateNotificationSettingsRequest) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateNotificationSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *NotificationSettings  `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotificationSettingsResponse) Reset() {
	*x = UpdateNotificationSettingsResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotificationSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotificationSettingsResponse) ProtoMessage() {}

func (x *UpdateNotificationSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotificationSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateNotificationSettingsResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateNotificationSettingsResponse) GetSettings() *NotificationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{22}
}

func (x *GetPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Preferences   *UserNotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{23}
}

func (x *GetPreferencesResponse) GetPreferences() *UserNotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesRequest struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	UserId          string                         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences     map[string]*ChannelPreferences `protobuf:"bytes,2,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EmailDigest     EmailDigest                    `protobuf:"varint,3,opt,name=email_digest,json=emailDigest,proto3,enum=konkosyuk.v1.EmailDigest" json:"email_digest,omitempty"`
	QuietHoursStart string                         `protobuf:"bytes,4,opt,name=quiet_hours_start,json=quietHoursStart,proto3" json:"quiet_hours_start,omitempty"`
	QuietHoursEnd   string                         `protobuf:"bytes,5,opt,name=quiet_hours_end,json=quietHoursEnd,proto3" json:"quiet_hours_end,omitempty"`
	Timezone        string                         `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{24}
}

func (x *UpdatePreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetPreferences() map[string]*ChannelPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UpdatePreferencesRequest) GetEmailDigest() EmailDigest {
	if x != nil {
		return x.EmailDigest
	}
	return EmailDigest_EMAIL_DIGEST_UNSPECIFIED
}

func (x *UpdatePreferencesRequest) GetQuietHoursStart() string {
	if x != nil {
		return x.QuietHoursStart
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetQuietHoursEnd() string {
	if x != nil {
		return x.QuietHoursEnd
	}
	return ""
}

func (x *UpdatePreferencesRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Preferences   *UserNotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_konkosyuk_v1_notification_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_konkosyuk_v1_notification_proto_rawDescGZIP(), []int{25}
}

func (x *UpdatePreferencesResponse) GetPreferences() *UserNotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_konkosyuk_v1_notification_proto protoreflect.FileDescriptor

const file_konkosyuk_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fkonkosyuk/v1/notification.proto\x12\fkonkosyuk.v1\x1a\x19konkosyuk/v1/common.proto\"U\n" +
	"\x12ChannelPreferences\x12\x15\n" +
	"\x06in_app\x18\x01 \x01(\bR\x05inApp\x12\x14\n" +
	"\x05email\x18\x02 \x01(\bR\x05email\x12\x12\n" +
	"\x04push\x18\x03 \x01(\bR\x04push\"\xf3\x02\n" +
	"\x0fUserPreferences\x12P\n" +
	"\vpreferences\x18\x01 \x03(\v2..konkosyuk.v1.UserPreferences.PreferencesEntryR\vpreferences\x12<\n" +
	"\femail_digest\x18\x02 \x01(\x0e2\x19.konkosyuk.v1.EmailDigestR\vemailDigest\x12*\n" +
	"\x11quiet_hours_start\x18\x03 \x01(\tR\x0fquietHoursStart\x12&\n" +
	"\x0fquiet_hours_end\x18\x04 \x01(\tR\rquietHoursEnd\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x1a`\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .konkosyuk.v1.ChannelPreferencesR\x05value:\x028\x01\"\x84\x04\n" +
	"\x11NotificationEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12>\n" +
	"\bcategory\x18\x03 \x01(\x0e2\".konkosyuk.v1.NotificationCategoryR\bcategory\x12>\n" +
	"\bpriority\x18\x04 \x01(\x0e2\".konkosyuk.v1.NotificationPriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"action_url\x18\a \x01(\tR\tactionUrl\x12!\n" +
	"\faction_label\x18\b \x01(\tR\vactionLabel\x12!\n" +
	"\freference_id\x18\t \x01(\tR\vreferenceId\x12%\n" +
	"\x0ereference_type\x18\n" +
	" \x01(\tR\rreferenceType\x12I\n" +
	"\bmetadata\x18\v \x03(\v2-.konkosyuk.v1.NotificationEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\x10DispatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12[\n" +
	"\x0fchannel_results\x18\x02 \x03(\v22.konkosyuk.v1.DispatchResponse.ChannelResultsEntryR\x0echannelResults\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1aA\n" +
	"\x13ChannelResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"O\n" +
	"\x14DispatchBatchRequest\x127\n" +
	"\x06events\x18\x01 \x03(\v2\x1f.konkosyuk.v1.NotificationEventR\x06events\"Q\n" +
	"\x15DispatchBatchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.konkosyuk.v1.DispatchResponseR\aresults\"\xd6\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12!\n" +
	"\freference_id\x18\x06 \x01(\tR\vreferenceId\x12\x17\n" +
	"\ais_read\x18\a \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xa2\x01\n" +
	"\x10PushSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06p256dh\x18\x04 \x01(\tR\x06p256dh\x12\x12\n" +
	"\x04auth\x18\x05 \x01(\tR\x04auth\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xa9\x03\n" +
	"\x14NotificationSettings\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eresend_api_key\x18\x02 \x01(\tR\fresendApiKey\x12*\n" +
	"\x11resend_from_email\x18\x03 \x01(\tR\x0fresendFromEmail\x12*\n" +
	"\x11meta_access_token\x18\x04 \x01(\tR\x0fmetaAccessToken\x12/\n" +
	"\x14meta_phone_number_id\x18\x05 \x01(\tR\x11metaPhoneNumberId\x12I\n" +
	"!meta_maintenance_created_template\x18\x06 \x01(\tR\x1emetaMaintenanceCreatedTemplate\x12I\n" +
	"!meta_maintenance_updated_template\x18\a \x01(\tR\x1emetaMaintenanceUpdatedTemplate\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xd3\x03\n" +
	"\x1bUserNotificationPreferences\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\\\n" +
	"\vpreferences\x18\x03 \x03(\v2:.konkosyuk.v1.UserNotificationPreferences.PreferencesEntryR\vpreferences\x12<\n" +
	"\femail_digest\x18\x04 \x01(\x0e2\x19.konkosyuk.v1.EmailDigestR\vemailDigest\x12*\n" +
	"\x11quiet_hours_start\x18\x05 \x01(\tR\x0fquietHoursStart\x12&\n" +
	"\x0fquiet_hours_end\x18\x06 \x01(\tR\rquietHoursEnd\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x1a`\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .konkosyuk.v1.ChannelPreferencesR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x19CreateNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"\\\n" +
	"\x1aCreateNotificationResponse\x12>\n" +
	"\fnotification\x18\x01 \x01(\v2\x1a.konkosyuk.v1.NotificationR\fnotification\"0\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"S\n" +
	"\x0fMarkReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\",\n" +
	"\x10MarkReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\x14SubscribePushRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06p256dh\x18\x03 \x01(\tR\x06p256dh\x12\x12\n" +
	"\x04auth\x18\x04 \x01(\tR\x04auth\"1\n" +
	"\x15SubscribePushResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x12GetSettingsRequest\x12)\n" +
	"\x05empty\x18\x01 \x01(\v2\x13.konkosyuk.v1.EmptyR\x05empty\"U\n" +
	"\x13GetSettingsResponse\x12>\n" +
	"\bsettings\x18\x01 \x01(\v2\".konkosyuk.v1.NotificationSettingsR\bsettings\"c\n" +
	"!UpdateNotificationSettingsRequest\x12>\n" +
	"\bsettings\x18\x01 \x01(\v2\".konkosyuk.v1.NotificationSettingsR\bsettings\"d\n" +
	"\"UpdateNotificationSettingsResponse\x12>\n" +
	"\bsettings\x18\x01 \x01(\v2\".konkosyuk.v1.NotificationSettingsR\bsettings\"0\n" +
	"\x15GetPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"e\n" +
	"\x16GetPreferencesResponse\x12K\n" +
	"\vpreferences\x18\x01 \x01(\v2).konkosyuk.v1.UserNotificationPreferencesR\vpreferences\"\x9e\x03\n" +
	"\x18UpdatePreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12Y\n" +
	"\vpreferences\x18\x02 \x03(\v27.konkosyuk.v1.UpdatePreferencesRequest.PreferencesEntryR\vpreferences\x12<\n" +
	"\femail_digest\x18\x03 \x01(\x0e2\x19.konkosyuk.v1.EmailDigestR\vemailDigest\x12*\n" +
	"\x11quiet_hours_start\x18\x04 \x01(\tR\x0fquietHoursStart\x12&\n" +
	"\x0fquiet_hours_end\x18\x05 \x01(\tR\rquietHoursEnd\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\x1a`\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .konkosyuk.v1.ChannelPreferencesR\x05value:\x028\x01\"h\n" +
	"\x19UpdatePreferencesResponse\x12K\n" +
	"\vpreferences\x18\x01 \x01(\v2).konkosyuk.v1.UserNotificationPreferencesR\vpreferences*\x9a\x01\n" +
	"\x14NotificationCategory\x12%\n" +
	"!NOTIFICATION_CATEGORY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aBOOKING\x10\x01\x12\v\n" +
	"\aPAYMENT\x10\x02\x12\x0f\n" +
	"\vMAINTENANCE\x10\x03\x12\x0e\n" +
	"\n" +
	"INSPECTION\x10\x04\x12\b\n" +
	"\x04CHAT\x10\x05\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x06\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\a*h\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\n" +
	"\n" +
	"\x06URGENT\x10\x04*\\\n" +
	"\vEmailDigest\x12\x1c\n" +
	"\x18EMAIL_DIGEST_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tIMMEDIATE\x10\x01\x12\t\n" +
	"\x05DAILY\x10\x02\x12\n" +
	"\n" +
	"\x06WEEKLY\x10\x03\x12\t\n" +
	"\x05NEVER\x10\x04*C\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06IN_APP\x10\x01\x12\t\n" +
	"\x05EMAIL\x10\x02\x12\b\n" +
	"\x04PUSH\x10\x032\xc7\x06\n" +
	"\x13NotificationService\x12K\n" +
	"\bDispatch\x12\x1f.konkosyuk.v1.NotificationEvent\x1a\x1e.konkosyuk.v1.DispatchResponse\x12U\n" +
	"\rDispatchBatch\x12\".konkosyuk.v1.DispatchBatchRequest\x1a\x1e.konkosyuk.v1.DispatchResponse0\x01\x12[\n" +
	"\x0eGetUnreadCount\x12#.konkosyuk.v1.GetUnreadCountRequest\x1a$.konkosyuk.v1.GetUnreadCountResponse\x12I\n" +
	"\bMarkRead\x12\x1d.konkosyuk.v1.MarkReadRequest\x1a\x1e.konkosyuk.v1.MarkReadResponse\x12X\n" +
	"\rSubscribePush\x12\".konkosyuk.v1.SubscribePushRequest\x1a#.konkosyuk.v1.SubscribePushResponse\x12R\n" +
	"\vGetSettings\x12 .konkosyuk.v1.GetSettingsRequest\x1a!.konkosyuk.v1.GetSettingsResponse\x12s\n" +
	"\x0eUpdateSettings\x12/.konkosyuk.v1.UpdateNotificationSettingsRequest\x1a0.konkosyuk.v1.UpdateNotificationSettingsResponse\x12[\n" +
	"\x0eGetPreferences\x12#.konkosyuk.v1.GetPreferencesRequest\x1a$.konkosyuk.v1.GetPreferencesResponse\x12d\n" +
	"\x11UpdatePreferences\x12&.konkosyuk.v1.UpdatePreferencesRequest\x1a'.konkosyuk.v1.UpdatePreferencesResponseB2\n" +
	"\x14com.konkosyuk.api.v1P\x01Z\x18notif/proto/konkosyuk/v1b\x06proto3"

var (
	file_konkosyuk_v1_notification_proto_rawDescOnce sync.Once
	file_konkosyuk_v1_notification_proto_rawDescData []byte
)

func file_konkosyuk_v1_notification_proto_rawDescGZIP() []byte {
	file_konkosyuk_v1_notification_proto_rawDescOnce.Do(func() {
		file_konkosyuk_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_konkosyuk_v1_notification_proto_rawDesc), len(file_konkosyuk_v1_notification_proto_rawDesc)))
	})
	return file_konkosyuk_v1_notification_proto_rawDescData
}

var file_konkosyuk_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_konkosyuk_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_konkosyuk_v1_notification_proto_goTypes = []any{
	(NotificationCategory)(0),                  // 0: konkosyuk.v1.NotificationCategory
	(NotificationPriority)(0),                  // 1: konkosyuk.v1.NotificationPriority
	(EmailDigest)(0),                           // 2: konkosyuk.v1.EmailDigest
	(Channel)(0),                               // 3: konkosyuk.v1.Channel
	(*ChannelPreferences)(nil),                 // 4: konkosyuk.v1.ChannelPreferences
	(*UserPreferences)(nil),                    // 5: konkosyuk.v1.UserPreferences
	(*NotificationEvent)(nil),                  // 6: konkosyuk.v1.NotificationEvent
	(*DispatchResponse)(nil),                   // 7: konkosyuk.v1.DispatchResponse
	(*DispatchBatchRequest)(nil),               // 8: konkosyuk.v1.DispatchBatchRequest
	(*DispatchBatchResponse)(nil),              // 9: konkosyuk.v1.DispatchBatchResponse
	(*Notification)(nil),                       // 10: konkosyuk.v1.Notification
	(*PushSubscription)(nil),                   // 11: konkosyuk.v1.PushSubscription
	(*NotificationSettings)(nil),               // 12: konkosyuk.v1.NotificationSettings
	(*UserNotificationPreferences)(nil),        // 13: konkosyuk.v1.UserNotificationPreferences
	(*CreateNotificationRequest)(nil),          // 14: konkosyuk.v1.CreateNotificationRequest
	(*CreateNotificationResponse)(nil),         // 15: konkosyuk.v1.CreateNotificationResponse
	(*GetUnreadCountRequest)(nil),              // 16: konkosyuk.v1.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),             // 17: konkosyuk.v1.GetUnreadCountResponse
	(*MarkReadRequest)(nil),                    // 18: konkosyuk.v1.MarkReadRequest
	(*MarkReadResponse)(nil),                   // 19: konkosyuk.v1.MarkReadResponse
	(*SubscribePushRequest)(nil),               // 20: konkosyuk.v1.SubscribePushRequest
	(*SubscribePushResponse)(nil),              // 21: konkosyuk.v1.SubscribePushResponse
	(*GetSettingsRequest)(nil),                 // 22: konkosyuk.v1.GetSettingsRequest
	(*GetSettingsResponse)(nil),                // 23: konkosyuk.v1.GetSettingsResponse
	(*UpdateNotificationSettingsRequest)(nil),  // 24: konkosyuk.v1.UpdateNotificationSettingsRequest
	(*UpdateNotificationSettingsResponse)(nil), // 25: konkosyuk.v1.UpdateNotificationSettingsResponse
	(*GetPreferencesRequest)(nil),              // 26: konkosyuk.v1.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),             // 27: konkosyuk.v1.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),           // 28: konkosyuk.v1.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil),          // 29: konkosyuk.v1.UpdatePreferencesResponse
	nil,                                        // 30: konkosyuk.v1.UserPreferences.PreferencesEntry
	nil,                                        // 31: konkosyuk.v1.NotificationEvent.MetadataEntry
	nil,                                        // 32: konkosyuk.v1.DispatchResponse.ChannelResultsEntry
	nil,                                        // 33: konkosyuk.v1.UserNotificationPreferences.PreferencesEntry
	nil,                                        // 34: konkosyuk.v1.UpdatePreferencesRequest.PreferencesEntry
	(*Empty)(nil),                              // 35: konkosyuk.v1.Empty
}
var file_konkosyuk_v1_notification_proto_depIdxs = []int32{
	30, // 0: konkosyuk.v1.UserPreferences.preferences:type_name -> konkosyuk.v1.UserPreferences.PreferencesEntry
	2,  // 1: konkosyuk.v1.UserPreferences.email_digest:type_name -> konkosyuk.v1.EmailDigest
	0,  // 2: konkosyuk.v1.NotificationEvent.category:type_name -> konkosyuk.v1.NotificationCategory
	1,  // 3: konkosyuk.v1.NotificationEvent.priority:type_name -> konkosyuk.v1.NotificationPriority
	31, // 4: konkosyuk.v1.NotificationEvent.metadata:type_name -> konkosyuk.v1.NotificationEvent.MetadataEntry
	32, // 5: konkosyuk.v1.DispatchResponse.channel_results:type_name -> konkosyuk.v1.DispatchResponse.ChannelResultsEntry
	6,  // 6: konkosyuk.v1.DispatchBatchRequest.events:type_name -> konkosyuk.v1.NotificationEvent
	7,  // 7: konkosyuk.v1.DispatchBatchResponse.results:type_name -> konkosyuk.v1.DispatchResponse
	33, // 8: konkosyuk.v1.UserNotificationPreferences.preferences:type_name -> konkosyuk.v1.UserNotificationPreferences.PreferencesEntry
	2,  // 9: konkosyuk.v1.UserNotificationPreferences.email_digest:type_name -> konkosyuk.v1.EmailDigest
	10, // 10: konkosyuk.v1.CreateNotificationResponse.notification:type_name -> konkosyuk.v1.Notification
	35, // 11: konkosyuk.v1.GetSettingsRequest.empty:type_name -> konkosyuk.v1.Empty
	12, // 12: konkosyuk.v1.GetSettingsResponse.settings:type_name -> konkosyuk.v1.NotificationSettings
	12, // 13: konkosyuk.v1.UpdateNotificationSettingsRequest.settings:type_name -> konkosyuk.v1.NotificationSettings
	12, // 14: konkosyuk.v1.UpdateNotificationSettingsResponse.settings:type_name -> konkosyuk.v1.NotificationSettings
	13, // 15: konkosyuk.v1.GetPreferencesResponse.preferences:type_name -> konkosyuk.v1.UserNotificationPreferences
	34, // 16: konkosyuk.v1.UpdatePreferencesRequest.preferences:type_name -> konkosyuk.v1.UpdatePreferencesRequest.PreferencesEntry
	2,  // 17: konkosyuk.v1.UpdatePreferencesRequest.email_digest:type_name -> konkosyuk.v1.EmailDigest
	13, // 18: konkosyuk.v1.UpdatePreferencesResponse.preferences:type_name -> konkosyuk.v1.UserNotificationPreferences
	4,  // 19: konkosyuk.v1.UserPreferences.PreferencesEntry.value:type_name -> konkosyuk.v1.ChannelPreferences
	4,  // 20: konkosyuk.v1.UserNotificationPreferences.PreferencesEntry.value:type_name -> konkosyuk.v1.ChannelPreferences
	4,  // 21: konkosyuk.v1.UpdatePreferencesRequest.PreferencesEntry.value:type_name -> konkosyuk.v1.ChannelPreferences
	6,  // 22: konkosyuk.v1.NotificationService.Dispatch:input_type -> konkosyuk.v1.NotificationEvent
	8,  // 23: konkosyuk.v1.NotificationService.DispatchBatch:input_type -> konkosyuk.v1.DispatchBatchRequest
	16, // 24: konkosyuk.v1.NotificationService.GetUnreadCount:input_type -> konkosyuk.v1.GetUnreadCountRequest
	18, // 25: konkosyuk.v1.NotificationService.MarkRead:input_type -> konkosyuk.v1.MarkReadRequest
	20, // 26: konkosyuk.v1.NotificationService.SubscribePush:input_type -> konkosyuk.v1.SubscribePushRequest
	22, // 27: konkosyuk.v1.NotificationService.GetSettings:input_type -> konkosyuk.v1.GetSettingsRequest
	24, // 28: konkosyuk.v1.NotificationService.UpdateSettings:input_type -> konkosyuk.v1.UpdateNotificationSettingsRequest
	26, // 29: konkosyuk.v1.NotificationService.GetPreferences:input_type -> konkosyuk.v1.GetPreferencesRequest
	28, // 30: konkosyuk.v1.NotificationService.UpdatePreferences:input_type -> konkosyuk.v1.UpdatePreferencesRequest
	7,  // 31: konkosyuk.v1.NotificationService.Dispatch:output_type -> konkosyuk.v1.DispatchResponse
	7,  // 32: konkosyuk.v1.NotificationService.DispatchBatch:output_type -> konkosyuk.v1.DispatchResponse
	17, // 33: konkosyuk.v1.NotificationService.GetUnreadCount:output_type -> konkosyuk.v1.GetUnreadCountResponse
	19, // 34: konkosyuk.v1.NotificationService.MarkRead:output_type -> konkosyuk.v1.MarkReadResponse
	21, // 35: konkosyuk.v1.NotificationService.SubscribePush:output_type -> konkosyuk.v1.SubscribePushResponse
	23, // 36: konkosyuk.v1.NotificationService.GetSettings:output_type -> konkosyuk.v1.GetSettingsResponse
	25, // 37: konkosyuk.v1.NotificationService.UpdateSettings:output_type -> konkosyuk.v1.UpdateNotificationSettingsResponse
	27, // 38: konkosyuk.v1.NotificationService.GetPreferences:output_type -> konkosyuk.v1.GetPreferencesResponse
	29, // 39: konkosyuk.v1.NotificationService.UpdatePreferences:output_type -> konkosyuk.v1.UpdatePreferencesResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_konkosyuk_v1_notification_proto_init() }
func file_konkosyuk_v1_notification_proto_init() {
	if File_konkosyuk_v1_notification_proto != nil {
		return
	}
	file_konkosyuk_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_konkosyuk_v1_notification_proto_rawDesc), len(file_konkosyuk_v1_notification_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_konkosyuk_v1_notification_proto_goTypes,
		DependencyIndexes: file_konkosyuk_v1_notification_proto_depIdxs,
		EnumInfos:         file_konkosyuk_v1_notification_proto_enumTypes,
		MessageInfos:      file_konkosyuk_v1_notification_proto_msgTypes,
	}.Build()
	File_konkosyuk_v1_notification_proto = out.File
	file_konkosyuk_v1_notification_proto_goTypes = nil
	file_konkosyuk_v1_notification_proto_depIdxs = nil
}
